USE DEMO_DB;

CREATE OR REPLACE TABLE CUSTOMER_ADDRESS_SAMPLE_5
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCDS_SF10TCL"."CUSTOMER_ADDRESS"
SAMPLE ROW (5) SEED(2);

CREATE OR REPLACE TABLE CUSTOMER_SAMPLE_1
AS
SELECT * FROM "SNOWFLAKE_SAMPLE_DATA"."TPCDS_SF10TCL"."CUSTOMER"
SAMPLE SYSTEM (1) SEED(2);

SELECT COUNT(*) FROM CUSTOMER_SAMPLE_1;