SHOW SHARES;

// Create share object
CREATE OR REPLACE SHARE COMEPLETE_SCHEMA_SHARE;

// Grant usage on dabase & schema
GRANT USAGE ON DATABASE OUR_FIRST_DB TO SHARE COMEPLETE_SCHEMA_SHARE;
GRANT USAGE ON SCHEMA OUR_FIRST_DB.PUBLIC TO SHARE COMEPLETE_SCHEMA_SHARE;

// Grant select on all tables
GRANT SELECT ON ALL TABLES IN SCHEMA OUR_FIRST_DB.PUBLIC TO SHARE COMEPLETE_SCHEMA_SHARE;
-- For all tables in database
-- GRANT SELECT ON ALL TABLES IN DATABASE OUR_FIRST_DB TO SHARE COMEPLETE_SCHEMA_SHARE;

SHOW MANAGED ACCOUNTS;

// Add account to share
ALTER SHARE COMEPLETE_SCHEMA_SHARE
ADD ACCOUNT=<account_name_consumer>;




---- In consumer/reader account ----

SHOW SHARES;

DESC SHARE <account_name_producer>.COMEPLETE_SCHEMA_SHARE;

CREATE OR REPLACE DATABASE DATA_SHARE_DB FROM SHARE <account_name_producer>.COMEPLETE_SCHEMA_SHARE;

SELECT * FROM  DATA_SHARE_DB.PUBLIC.ORDERS;



---- In producer account ----


// Updating data
UPDATE OUR_FIRST_DB.PUBLIC.ORDERS
SET PROFIT=0 WHERE PROFIT < 0;

// Add new table
CREATE TABLE OUR_FIRST_DB.PUBLIC.NEW_TABLE (ID int);





---- In consumer/reader account ----

SELECT * FROM  DATA_SHARE_DB.PUBLIC.ORDERS;

-- Fails as newly created table is not granted select permission on
SELECT * FROM  DATA_SHARE_DB.PUBLIC.NEW_TABLE;
