CREATE SECURE VIEW SECURE_VIEW_M AS
SELECT
T1.ID,
T1.FIRST_NAME,
T2.JOB
FROM CUSTOMER_DB.PUBLIC.CUSTOMERS T1
INNER JOIN  OUR_FIRST_DB.PUBLIC.CUSTOMERS T2
ON T1.ID = T2.ID;

SELECT * FROM SECURE_VIEW_M;


SHOW SHARES;

// Create share object
CREATE OR REPLACE SHARE VIEW_SHARE_M;

// Grant usage on dabase & schema
GRANT USAGE ON DATABASE CUSTOMER_DB TO SHARE VIEW_SHARE_M;
GRANT USAGE ON SCHEMA CUSTOMER_DB.PUBLIC TO SHARE VIEW_SHARE_M;


// Grant select on view
GRANT SELECT ON VIEW  CUSTOMER_DB.PUBLIC.SECURE_VIEW_M TO SHARE VIEW_SHARE_M;

GRANT REFERENCE_USAGE ON DATABASE OUR_FIRST_DB TO SHARE VIEW_SHARE_M;

GRANT SELECT ON VIEW  CUSTOMER_DB.PUBLIC.SECURE_VIEW_M TO SHARE VIEW_SHARE_M;

// Add account to share
ALTER SHARE VIEW_SHARE_M
ADD ACCOUNT=<account_name_consumer>;


---- In consumer account ----

SHOW SHARES;

DESC SHARE <account_name_producer>.VIEW_SHARE_M;

CREATE OR REPLACE DATABASE DATA_SHARE_DB_M FROM SHARE <account_name_producer>.VIEW_SHARE_M;