CREATE OR REPLACE TRANSIENT DATABASE SAMPLING_DB;

-- Syntax: SELECT * FROM [table] SAMPLE [sampleMethod(ROW/ SYSTEM)] ([percentage]) [SEED([seedValue])]
-- Seed is used to get consistent sampling even though random but same entries

CREATE OR REPLACE VIEW ADDRESS_SAMPLE
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS
SAMPLE ROW (1) SEED(27);

SELECT * FROM ADDRESS_SAMPLE;



SELECT CA_LOCATION_TYPE, COUNT(*)/500200*100
FROM ADDRESS_SAMPLE
GROUP BY CA_LOCATION_TYPE;


CREATE OR REPLACE VIEW ADDRESS_SAMPLE_2
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS
SAMPLE SYSTEM (1) SEED(23);

SELECT * FROM ADDRESS_SAMPLE_2;

SELECT CA_LOCATION_TYPE, COUNT(*)/756700*100
FROM ADDRESS_SAMPLE_2
GROUP BY CA_LOCATION_TYPE;
